souffle: souffle::RamRelationSize Class Reference
souffle::RamRelationSize Class Reference
Returns the numbers of tuples in a relation.
#include <RelationSize.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamRelationSize * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get relation.
RamRelationSize (Own< RamRelationReference > relRef)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, Own< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< RamRelationReference > relationRef
Relation.
Detailed Description
Returns the numbers of tuples in a relation.
For example:
size(B)
Definition at line 43 of file RelationSize.h.
Constructor & Destructor Documentation
RamRelationSize()
souffle::RamRelationSize::RamRelationSize (Own< RamRelationReference > relRef) inline
Definition at line 45 of file RelationSize.h.
References relationRef.
Referenced by clone().
                                                       : relationRef(std::move(relRef)) {
         assert(relationRef != nullptr && "Relation reference is a nullptr");
     }
Member Function Documentation
apply()
void souffle::RamRelationSize::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 62 of file RelationSize.h.
References souffle::map(), and relationRef.
{
         relationRef = map(std::move(relationRef));
     }
clone()
RamRelationSize* souffle::RamRelationSize::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamExpression.
Definition at line 58 of file RelationSize.h.
References souffle::clone(), RamRelationSize(), and relationRef.
{
         return new RamRelationSize(souffle::clone(relationRef));
     }
equal()
bool souffle::RamRelationSize::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 71 of file RelationSize.h.
References souffle::equal_ptr(), and relationRef.
{
         const auto& other = static_cast<const RamRelationSize&>(node);
         return equal_ptr(relationRef, other.relationRef);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamRelationSize::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 54 of file RelationSize.h.
References relationRef.
{
         return {relationRef.get()};
     }
getRelation()
const RamRelation& souffle::RamRelationSize::getRelation () const inline
Get relation.
Definition at line 50 of file RelationSize.h.
References relationRef.
Referenced by souffle::Synthesiser::emitCode(), print(), and souffle::NodeGenerator::visitRelationSize().
{
         return *relationRef->get();
     }
print()
void souffle::RamRelationSize::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 67 of file RelationSize.h.
References souffle::RamRelation::getName(), and getRelation().
{
         os << "size(" << getRelation().getName() << ")";
     }
Field Documentation
relationRef
Own<RamRelationReference> souffle::RamRelationSize::relationRef protected
Relation.
Definition at line 77 of file RelationSize.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRelation(), and RamRelationSize().
The documentation for this class was generated from the following file:
ram/RelationSize.h