souffle: souffle::AstDirective Class Reference
souffle::AstDirective Class Reference
a directive has a type (e.g.
#include <Directive.h>
Public Member Functions
void addDirective (const std::string &key, std::string value)
Add new parameter.
AstDirective (AstDirectiveType type, AstQualifiedName name, SrcLocation loc={})
AstDirective * clone () const override
Create a clone (i.e.
const std::string & getDirective (const std::string &key) const
Get parameter.
const std::map< std::string, std::string > & getDirectives () const
Get parameters.
const AstQualifiedName & getQualifiedName () const
Get relation name.
AstDirectiveType getType () const
Get directive type.
bool hasDirective (const std::string &key) const
Check for a parameter.
void setQualifiedName (AstQualifiedName name)
Set relation name.
void setType (AstDirectiveType type)
Set directive type.
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::map< std::string, std::string > directives
Parameters of directive.
AstQualifiedName name
Relation name of the directive.
AstDirectiveType type
Type of directive.
Detailed Description
a directive has a type (e.g.
input/output/printsize/limitsize), qualified relation name, and a key value map for storing parameters of the directive.
Definition at line 50 of file Directive.h.
Constructor & Destructor Documentation
AstDirective()
souffle::AstDirective::AstDirective (AstDirectiveType type, AstQualifiedName name, SrcLocation loc = {}) inline
Definition at line 52 of file Directive.h.
                                                                                  {})
             : AstNode(std::move(loc)), type(type), name(std::move(name)) {}
Member Function Documentation
addDirective()
void souffle::AstDirective::addDirective (const std::string & key, std::string value) inline
Add new parameter.
Definition at line 81 of file Directive.h.
References directives.
{
         directives[key] = std::move(value);
     }
clone()
AstDirective* souffle::AstDirective::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 95 of file Directive.h.
References directives.
{
         auto res = new AstDirective(type, name, getSrcLoc());
         res->directives = directives;
         return res;
     }
equal()
bool souffle::AstDirective::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 111 of file Directive.h.
References directives, and type.
{
         const auto& other = static_cast<const AstDirective&>(node);
         return other.type == type && other.name == name && other.directives == directives;
     }
getDirective()
const std::string& souffle::AstDirective::getDirective (const std::string & key) const inline
Get parameter.
Definition at line 76 of file Directive.h.
References directives.
Referenced by souffle::IOType::run().
{
         return directives.at(key);
     }
getDirectives()
const std::map<std::string, std::string>& souffle::AstDirective::getDirectives () const inline
Get parameters.
Definition at line 91 of file Directive.h.
References directives.
{
         return directives;
     }
getQualifiedName()
const AstQualifiedName& souffle::AstDirective::getQualifiedName () const inline
Get relation name.
Definition at line 66 of file Directive.h.
Referenced by souffle::IODefaultsTransformer::getRelationName(), souffle::IOAttributesTransformer::getRelationName(), and souffle::IOType::run().
{
         return name;
     }
getType()
AstDirectiveType souffle::AstDirective::getType () const inline
Get directive type.
Definition at line 56 of file Directive.h.
Referenced by souffle::IOType::run().
{
         return type;
     }
hasDirective()
bool souffle::AstDirective::hasDirective (const std::string & key) const inline
Check for a parameter.
Definition at line 86 of file Directive.h.
References directives.
Referenced by souffle::IOType::run().
{
         return directives.find(key) != directives.end();
     }
print()
void souffle::AstDirective::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 102 of file Directive.h.
References directives, and souffle::join().
{
         os << "." << type << " " << name;
         if (!directives.empty()) {
             os << "(" << join(directives, ",", [](std::ostream& out, const auto& arg) {
                 out << arg.first << "=\"" << arg.second << "\"";
             }) << ")";
         }
     }
setQualifiedName()
void souffle::AstDirective::setQualifiedName (AstQualifiedName name) inline
Set relation name.
Definition at line 71 of file Directive.h.
{
         this->name = std::move(name);
     }
setType()
void souffle::AstDirective::setType (AstDirectiveType type) inline
Set directive type.
Definition at line 61 of file Directive.h.
{
         this->type = type;
     }
Field Documentation
directives
std::map<std::string, std::string> souffle::AstDirective::directives protected
Parameters of directive.
Definition at line 123 of file Directive.h.
name
AstQualifiedName souffle::AstDirective::name protected
Relation name of the directive.
Definition at line 120 of file Directive.h.
type
AstDirectiveType souffle::AstDirective::type protected
Type of directive.
Definition at line 117 of file Directive.h.
Referenced by equal().
The documentation for this class was generated from the following file:
ast/Directive.h