souffle: souffle::RamNegation Class Reference
souffle::RamNegation Class Reference
Negates a given condition.
#include <Negation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamNegation * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamCondition & getOperand () const
Get operand of negation.
RamNegation (Own< RamCondition > op)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, Own< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
Own< RamCondition > operand
Operand.
Detailed Description
Negates a given condition.
For example:
(NOT t0 IN A)
Definition at line 42 of file Negation.h.
Constructor & Destructor Documentation
RamNegation()
souffle::RamNegation::RamNegation (Own< RamCondition > op) inline
Definition at line 44 of file Negation.h.
References operand.
Referenced by clone().
                                       : operand(std::move(op)) {
         assert(operand != nullptr && "operand of negation is a null-pointer");
     }
Member Function Documentation
apply()
void souffle::RamNegation::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 61 of file Negation.h.
References souffle::map(), and operand.
{
         operand = map(std::move(operand));
     }
clone()
RamNegation* souffle::RamNegation::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamCondition.
Definition at line 57 of file Negation.h.
References souffle::clone(), operand, and RamNegation().
{
         return new RamNegation(souffle::clone(operand));
     }
equal()
bool souffle::RamNegation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 70 of file Negation.h.
References souffle::equal_ptr(), and operand.
{
         const auto& other = static_cast<const RamNegation&>(node);
         return equal_ptr(operand, other.operand);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamNegation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 53 of file Negation.h.
References operand.
{
         return {operand.get()};
     }
getOperand()
const RamCondition& souffle::RamNegation::getOperand () const inline
Get operand of negation.
Definition at line 49 of file Negation.h.
References operand.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamComplexityAnalysis::getComplexity(), and souffle::RamLevelAnalysis::getLevel().
{
         return *operand;
     }
print()
void souffle::RamNegation::print (std::ostream & out) const inline override protected virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 66 of file Negation.h.
References operand.
{
         os << "(NOT " << *operand << ")";
     }
Field Documentation
operand
Own<RamCondition> souffle::RamNegation::operand protected
Operand.
Definition at line 76 of file Negation.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getOperand(), print(), and RamNegation().
The documentation for this class was generated from the following file:
ram/Negation.h