souffle: souffle::AstProgram Class Reference
souffle::AstProgram Class Reference
The program class consists of relations, clauses and types.
#include <Program.h>
Public Member Functions
void addClause (Own< AstClause > clause)
Add a clause.
void addDirective (Own< AstDirective > directive)
Add relation directive.
void addRelation (Own< AstRelation > relation)
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstProgram * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
Return clauses.
std::vector< AstComponentInit * > getComponentInstantiations () const
Return component instantiation.
std::vector< AstComponent * > getComponents () const
Return components.
std::vector< AstDirective * > getDirectives () const
Return relation directives.
std::vector< AstFunctorDeclaration * > getFunctorDeclarations () const
Return functor declarations.
const VecOwn< AstPragma > & getPragmaDirectives () const
Return pragma directives.
std::vector< AstRelation * > getRelations () const
Return relations.
std::vector< AstType * > getTypes () const
Return types.
bool removeClause (const AstClause *clause)
Remove a clause.
bool removeDirective (const AstDirective *directive)
Remove a directive.
bool removeRelationDecl (const AstQualifiedName &name)
Remove relation.
void setClauses (VecOwn< AstClause > newClauses)
Set clauses.
Public Member Functions inherited from souffle::AstNode
AstNode (SrcLocation loc={})
std::string extloc () const
Return source location of the syntactic element.
const SrcLocation & getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (SrcLocation l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void addComponent (Own< AstComponent > component)
Add component.
void addFunctorDeclaration (Own< souffle::AstFunctorDeclaration > functor)
void addInstantiation (Own< AstComponentInit > instantiation)
Add component instantiation.
void addPragma (Own< AstPragma > pragma)
void addType (Own< AstType > type)
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
VecOwn< AstClause > clauses
Program clauses.
VecOwn< AstComponent > components
Component definitions.
VecOwn< AstDirective > directives
Directives.
VecOwn< AstFunctorDeclaration > functors
External Functors.
VecOwn< AstComponentInit > instantiations
Component instantiations.
VecOwn< AstPragma > pragmas
Pragmas.
VecOwn< AstRelation > relations
Program relations.
VecOwn< AstType > types
Program types.
Friends
class ComponentInstantiationTransformer
class ParserDriver
Detailed Description
The program class consists of relations, clauses and types.
Definition at line 46 of file Program.h.
Member Function Documentation
addClause()
void souffle::AstProgram::addClause (Own< AstClause > clause)
Add a clause.
Definition at line 54 of file Program.cpp.
References clauses.
Referenced by souffle::makeInfoRelation(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::normaliseInlinedHeads(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), setClauses(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::AddNullariesToAtomlessAggregatesTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::ResolveAliasesTransformer::transform(), and souffle::transformEqrelRelation().
{
     assert(clause != nullptr && "Undefined clause");
     assert(clause->getHead() != nullptr && "Undefined head of the clause");
     clauses.push_back(std::move(clause));
 }
addComponent()
void souffle::AstProgram::addComponent (Own< AstComponent > component) inline protected
Add component.
Definition at line 239 of file Program.h.
References components.
{
         assert(component && "NULL component");
         components.push_back(std::move(component));
     }
addDirective()
void souffle::AstProgram::addDirective (Own< AstDirective > directive) inline
Add relation directive.
Definition at line 74 of file Program.h.
References directives.
Referenced by souffle::IODefaultsTransformer::setDefaults().
{
         assert(directive && "NULL directive");
         directives.push_back(std::move(directive));
     }
addFunctorDeclaration()
void souffle::AstProgram::addFunctorDeclaration (Own< souffle::AstFunctorDeclaration > functor) protected
Definition at line 92 of file Program.cpp.
References functors, getFunctorDeclarations(), souffle::getIf(), and souffle::AstFunctorDeclaration::getName().
{
     auto* existingFunctorDecl = getIf(getFunctorDeclarations(),
             [&](const AstFunctorDeclaration* current) { return current->getName() == f->getName(); });
     assert(existingFunctorDecl == nullptr && "Redefinition of functor!");
     functors.push_back(std::move(f));
 }
addInstantiation()
void souffle::AstProgram::addInstantiation (Own< AstComponentInit > instantiation) inline protected
Add component instantiation.
Definition at line 245 of file Program.h.
References instantiations.
{
         assert(instantiation && "NULL instantiation");
         instantiations.push_back(std::move(instantiation));
     }
addPragma()
void souffle::AstProgram::addPragma (Own< AstPragma > pragma) protected
Definition at line 87 of file Program.cpp.
References pragmas.
{
     assert(pragma && "NULL pragma");
     pragmas.push_back(std::move(pragma));
 }
addRelation()
void souffle::AstProgram::addRelation (Own< AstRelation > relation)
Definition at line 35 of file Program.cpp.
References souffle::getIf(), souffle::AstRelation::getQualifiedName(), getRelations(), and relations.
Referenced by getPragmaDirectives(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::ReduceExistentialsTransformer::transform(), souffle::MaterializeSingletonAggregationTransformer::transform(), souffle::AddNullariesToAtomlessAggregatesTransformer::transform(), and souffle::PartitionBodyLiteralsTransformer::transform().
{
     auto* existingRelation = getIf(getRelations(), [&](const AstRelation* current) {
         return current->getQualifiedName() == relation->getQualifiedName();
     });
     assert(existingRelation == nullptr && "Redefinition of relation!");
     relations.push_back(std::move(relation));
 }
addType()
void souffle::AstProgram::addType (Own< AstType > type) protected
Definition at line 80 of file Program.cpp.
References souffle::getIf(), souffle::AstType::getQualifiedName(), getTypes(), and types.
{
     auto* existingType = getIf(getTypes(),
             [&](const AstType* current) { return current->getQualifiedName() == type->getQualifiedName(); });
     assert(existingType == nullptr && "Redefinition of type!");
     types.push_back(std::move(type));
 }
apply()
void souffle::AstProgram::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 127 of file Program.h.
References clauses, components, directives, functors, instantiations, souffle::map(), pragmas, relations, and types.
Referenced by souffle::nameInlinedUnderscores(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveTypecastsTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::ADTtoRecordsTransformer::transform(), souffle::RemoveRedundantSumsTransformer::transform(), souffle::AstUserDefinedFunctorsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), and souffle::NameUnnamedVariablesTransformer::transform().
{
         for (auto& cur : pragmas) {
             cur = map(std::move(cur));
         }
         for (auto& cur : components) {
             cur = map(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : functors) {
             cur = map(std::move(cur));
         }
         for (auto& cur : types) {
             cur = map(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = map(std::move(cur));
         }
         for (auto& cur : directives) {
             cur = map(std::move(cur));
         }
     }
clone()
AstProgram* souffle::AstProgram::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 114 of file Program.h.
References clauses, souffle::clone(), components, directives, functors, instantiations, pragmas, relations, and types.
{
         auto res = new AstProgram();
         res->pragmas = souffle::clone(pragmas);
         res->components = souffle::clone(components);
         res->instantiations = souffle::clone(instantiations);
         res->types = souffle::clone(types);
         res->functors = souffle::clone(functors);
         res->relations = souffle::clone(relations);
         res->clauses = souffle::clone(clauses);
         res->directives = souffle::clone(directives);
         return res;
     }
equal()
bool souffle::AstProgram::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 199 of file Program.h.
References clauses, components, directives, souffle::equal_targets(), functors, instantiations, pragmas, relations, and types.
{
         const auto& other = static_cast<const AstProgram&>(node);
         if (!equal_targets(pragmas, other.pragmas)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(functors, other.functors)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(directives, other.directives)) {
             return false;
         }
         return true;
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstProgram::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 154 of file Program.h.
References clauses, components, directives, functors, instantiations, pragmas, relations, and types.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : pragmas) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : functors) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : directives) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstProgram::getClauses () const inline
Return clauses.
Definition at line 59 of file Program.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::AstSemanticCheckerImpl::checkBranchInits(), souffle::getClauses(), souffle::TypeAnalysis::run(), souffle::TypeChecker::run(), souffle::ResolveAnonymousRecordAliases::transform(), souffle::FoldAnonymousRecords::transform(), and souffle::ReorderLiteralsTransformer::transform().
{
         return toPtrVector(clauses);
     }
getComponentInstantiations()
std::vector<AstComponentInit*> souffle::AstProgram::getComponentInstantiations () const inline
Return component instantiation.
Definition at line 110 of file Program.h.
References instantiations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), and souffle::AstComponentChecker::checkComponents().
{
         return toPtrVector(instantiations);
     }
getComponents()
std::vector<AstComponent*> souffle::AstProgram::getComponents () const inline
Return components.
Definition at line 105 of file Program.h.
References components, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstComponentChecker::checkComponents(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getDirectives()
std::vector<AstDirective*> souffle::AstProgram::getDirectives () const inline
Return relation directives.
Definition at line 69 of file Program.h.
References directives, and souffle::toPtrVector().
Referenced by souffle::AstSemanticCheckerImpl::checkIO(), souffle::getDirectives(), souffle::AstToRamTranslator::getInputDirectives(), souffle::AstToRamTranslator::getOutputDirectives(), souffle::IOAttributesTransformer::setAttributeNames(), souffle::IOAttributesTransformer::setAttributeParams(), souffle::IOAttributesTransformer::setAttributeTypes(), and souffle::IODefaultsTransformer::setDefaults().
{
         return toPtrVector(directives);
     }
getFunctorDeclarations()
std::vector<AstFunctorDeclaration*> souffle::AstProgram::getFunctorDeclarations () const inline
Return functor declarations.
Definition at line 64 of file Program.h.
References functors, and souffle::toPtrVector().
Referenced by addFunctorDeclaration(), and souffle::AstUserDefinedFunctorsTransformer::transform().
{
         return toPtrVector(functors);
     }
getPragmaDirectives()
const VecOwn<AstPragma>& souffle::AstProgram::getPragmaDirectives () const inline
Return pragma directives.
Definition at line 80 of file Program.h.
References addRelation(), pragmas, relation, and removeRelationDecl().
{
         return pragmas;
     }
getRelations()
std::vector<AstRelation*> souffle::AstProgram::getRelations () const inline
Return relations.
Definition at line 54 of file Program.h.
References relations, and souffle::toPtrVector().
Referenced by addRelation(), souffle::AstSemanticCheckerImpl::AstSemanticCheckerImpl(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticCheckerImpl::checkInlining(), souffle::AstSemanticCheckerImpl::checkNamespaces(), souffle::getRelation(), souffle::nameInlinedUnderscores(), souffle::normaliseInlinedHeads(), souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::MinimiseProgramTransformer::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RedundantRelationsAnalysis::run(), souffle::SCCGraphAnalysis::run(), souffle::test::TEST(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), and souffle::NameUnnamedVariablesTransformer::transform().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<AstType*> souffle::AstProgram::getTypes () const inline
Return types.
Definition at line 49 of file Program.h.
References souffle::toPtrVector(), and types.
Referenced by addType(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticCheckerImpl::checkNamespaces(), souffle::AstSemanticCheckerImpl::checkRelationDeclaration(), souffle::AstSemanticCheckerImpl::checkTypesDeclarations(), souffle::AstSemanticCheckerImpl::checkUnionType(), souffle::IOAttributesTransformer::getAlgebraicDataTypes(), souffle::IOAttributesTransformer::getRecordsParams(), souffle::IOAttributesTransformer::getRecordsTypes(), souffle::SumTypeBranchesAnalysis::run(), and souffle::TypeEnvironmentAnalysis::run().
{
         return toPtrVector(types);
     }
print()
void souffle::AstProgram::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 184 of file Program.h.
References clauses, components, directives, functors, instantiations, souffle::join(), pragmas, relations, and types.
{
         auto show = [&](auto&& xs, char const* sep = "\n") {
             if (!xs.empty()) os << join(xs, sep) << "\n";
         };
         show(pragmas, "\n\n");
         show(components);
         show(instantiations);
         show(types);
         show(functors);
         show(relations);
         show(clauses, "\n\n");
         show(directives, "\n\n");
     }
removeClause()
bool souffle::AstProgram::removeClause (const AstClause * clause)
Remove a clause.
Definition at line 60 of file Program.cpp.
References clauses.
Referenced by souffle::normaliseInlinedHeads(), souffle::MinimiseProgramTransformer::reduceClauseBodies(), souffle::MinimiseProgramTransformer::reduceLocallyEquivalentClauses(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::MinimiseProgramTransformer::removeRedundantClauses(), souffle::removeRelationClauses(), setClauses(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), and souffle::ResolveAliasesTransformer::transform().
{
     for (auto it = clauses.begin(); it != clauses.end(); it++) {
         if (**it == *clause) {
             clauses.erase(it);
             return true;
         }
     }
     return false;
 }
removeDirective()
bool souffle::AstProgram::removeDirective (const AstDirective * directive)
Remove a directive.
Definition at line 70 of file Program.cpp.
References directives.
Referenced by souffle::removeRelationIOs(), and setClauses().
{
     for (auto it = directives.begin(); it != directives.end(); it++) {
         if (**it == *directive) {
             directives.erase(it);
             return true;
         }
     }
     return false;
 }
removeRelationDecl()
bool souffle::AstProgram::removeRelationDecl (const AstQualifiedName & name)
Remove relation.
Definition at line 43 of file Program.cpp.
References relations.
Referenced by getPragmaDirectives(), and souffle::removeRelation().
{
     for (auto it = relations.begin(); it != relations.end(); it++) {
         const auto& rel = *it;
         if (rel->getQualifiedName() == name) {
             relations.erase(it);
             return true;
         }
     }
     return false;
 }
setClauses()
void souffle::AstProgram::setClauses (VecOwn< AstClause > newClauses) inline
Set clauses.
Definition at line 91 of file Program.h.
References addClause(), clauses, removeClause(), and removeDirective().
Referenced by souffle::FoldAnonymousRecords::transform().
{
         clauses = std::move(newClauses);
     }
Friends And Related Function Documentation
ComponentInstantiationTransformer
friend class ComponentInstantiationTransformer friend
Definition at line 229 of file Program.h.
ParserDriver
friend class ParserDriver friend
Definition at line 230 of file Program.h.
Field Documentation
clauses
VecOwn<AstClause> souffle::AstProgram::clauses protected
Program clauses.
Definition at line 260 of file Program.h.
Referenced by addClause(), apply(), clone(), equal(), getChildNodes(), getClauses(), print(), removeClause(), setClauses(), and souffle::ComponentInstantiationTransformer::transform().
components
VecOwn<AstComponent> souffle::AstProgram::components protected
Component definitions.
Definition at line 266 of file Program.h.
Referenced by addComponent(), apply(), clone(), equal(), getChildNodes(), getComponents(), print(), and souffle::ComponentInstantiationTransformer::transform().
directives
VecOwn<AstDirective> souffle::AstProgram::directives protected
Directives.
Definition at line 263 of file Program.h.
Referenced by addDirective(), apply(), clone(), equal(), getChildNodes(), getDirectives(), print(), removeDirective(), and souffle::ComponentInstantiationTransformer::transform().
functors
VecOwn<AstFunctorDeclaration> souffle::AstProgram::functors protected
External Functors.
Definition at line 257 of file Program.h.
Referenced by addFunctorDeclaration(), apply(), clone(), equal(), getChildNodes(), getFunctorDeclarations(), and print().
instantiations
VecOwn<AstComponentInit> souffle::AstProgram::instantiations protected
Component instantiations.
Definition at line 269 of file Program.h.
Referenced by addInstantiation(), apply(), clone(), equal(), getChildNodes(), getComponentInstantiations(), print(), and souffle::ComponentInstantiationTransformer::transform().
pragmas
VecOwn<AstPragma> souffle::AstProgram::pragmas protected
Pragmas.
Definition at line 272 of file Program.h.
Referenced by addPragma(), apply(), clone(), equal(), getChildNodes(), getPragmaDirectives(), and print().
relations
VecOwn<AstRelation> souffle::AstProgram::relations protected
Program relations.
Definition at line 254 of file Program.h.
Referenced by addRelation(), apply(), clone(), equal(), getChildNodes(), getRelations(), print(), removeRelationDecl(), and souffle::ComponentInstantiationTransformer::transform().
types
VecOwn<AstType> souffle::AstProgram::types protected
Program types.
Definition at line 251 of file Program.h.
Referenced by addType(), apply(), clone(), equal(), getChildNodes(), getTypes(), print(), and souffle::ComponentInstantiationTransformer::transform().
The documentation for this class was generated from the following files:
ast/Program.h
ast/Program.cpp