souffle: souffle::RamProject Class Reference
souffle::RamProject Class Reference
Project a result into the target relation.
#include <Project.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamProject * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
const RamRelation & getRelation () const
Get relation.
std::vector< RamExpression * > getValues () const
Get expressions.
RamProject (Own< RamRelationReference > relRef, VecOwn< RamExpression > expressions)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, Own< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
VecOwn< RamExpression > expressions
Own< RamRelationReference > relationRef
Relation that values are projected into.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Project a result into the target relation.
For example:
FOR t0 IN A
  ...
    PROJECT (t0.a, t0.b, t0.c) INTO @new_X
Definition at line 46 of file Project.h.
Constructor & Destructor Documentation
RamProject()
souffle::RamProject::RamProject (Own< RamRelationReference > relRef, VecOwn< RamExpression > expressions) inline
Definition at line 48 of file Project.h.
References relationRef.
Referenced by clone().
             : relationRef(std::move(relRef)), expressions(std::move(expressions)) {
         assert(relationRef != nullptr && "Relation reference is a null-pointer");
         for (auto const& expr : expressions) {
             assert(expr != nullptr && "Expression is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamProject::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 83 of file Project.h.
References expressions, souffle::map(), and relationRef.
{
         relationRef = map(std::move(relationRef));
         for (auto& expr : expressions) {
             expr = map(std::move(expr));
         }
     }
clone()
RamProject* souffle::RamProject::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 75 of file Project.h.
References souffle::clone(), expressions, RamProject(), and relationRef.
Referenced by souffle::test::TEST().
{
         VecOwn<RamExpression> newValues;
         for (auto& expr : expressions) {
             newValues.emplace_back(expr->clone());
         }
         return new RamProject(souffle::clone(relationRef), std::move(newValues));
     }
equal()
bool souffle::RamProject::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 97 of file Project.h.
References souffle::equal_ptr(), souffle::equal_targets(), expressions, and relationRef.
{
         const auto& other = static_cast<const RamProject&>(node);
         return equal_ptr(relationRef, other.relationRef) && equal_targets(expressions, other.expressions);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamProject::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 66 of file Project.h.
References expressions, and relationRef.
{
         std::vector<const RamNode*> res;
         res.push_back(relationRef.get());
         for (const auto& expr : expressions) {
             res.push_back(expr.get());
         }
         return res;
     }
getRelation()
const RamRelation& souffle::RamProject::getRelation () const inline
Get relation.
Definition at line 57 of file Project.h.
References relationRef.
Referenced by souffle::Synthesiser::emitCode(), souffle::NodeGenerator::getProjectSuperInstInfo(), print(), and souffle::NodeGenerator::visitProject().
{
         return *relationRef->get();
     }
getValues()
std::vector<RamExpression*> souffle::RamProject::getValues () const inline
Get expressions.
Definition at line 62 of file Project.h.
References expressions, and souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), and souffle::NodeGenerator::getProjectSuperInstInfo().
{
         return toPtrVector(expressions);
     }
print()
void souffle::RamProject::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamOperation.
Definition at line 91 of file Project.h.
References expressions, souffle::RamRelation::getName(), getRelation(), souffle::join(), and souffle::times().
{
         os << times(" ", tabpos);
         os << "PROJECT (" << join(expressions, ", ", print_deref<Own<RamExpression>>()) << ") INTO "
            << getRelation().getName() << std::endl;
     }
Field Documentation
expressions
VecOwn<RamExpression> souffle::RamProject::expressions protected
Definition at line 106 of file Project.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getValues(), and print().
relationRef
Own<RamRelationReference> souffle::RamProject::relationRef protected
Relation that values are projected into.
Definition at line 103 of file Project.h.
Referenced by apply(), clone(), equal(), getChildNodes(), getRelation(), and RamProject().
The documentation for this class was generated from the following file:
ram/Project.h