souffle: souffle::IOType Class Reference
souffle::IOType Class Reference
#include <IOType.h>
Public Member Functions
std::size_t getLimitSize (const AstRelation *relation) const
IOType ()
bool isInput (const AstRelation *relation) const
bool isIO (const AstRelation *relation) const
bool isLimitSize (const AstRelation *relation) const
bool isOutput (const AstRelation *relation) const
bool isPrintSize (const AstRelation *relation) const
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Attributes
static constexpr const char * name = "IO-type-analysis"
Private Attributes
std::set< const AstRelation * > inputRelations
std::map< const AstRelation *, std::size_t > limitSize
std::set< const AstRelation * > limitSizeRelations
std::set< const AstRelation * > outputRelations
std::set< const AstRelation * > printSizeRelations
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 31 of file IOType.h.
Constructor & Destructor Documentation
IOType()
souffle::IOType::IOType () inline
Definition at line 35 of file IOType.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
getLimitSize()
std::size_t souffle::IOType::getLimitSize (const AstRelation * relation) const inline
Definition at line 57 of file IOType.h.
References limitSize.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         auto iter = limitSize.find(relation);
         if (iter != limitSize.end()) {
             return (*iter).second;
         } else
             return 0;
     }
isInput()
bool souffle::IOType::isInput (const AstRelation * relation) const inline
Definition at line 41 of file IOType.h.
References inputRelations.
Referenced by souffle::AstSemanticCheckerImpl::checkRelation(), souffle::SCCGraphAnalysis::getInternalInputRelations(), and isIO().
{
         return inputRelations.count(relation) != 0;
     }
isIO()
bool souffle::IOType::isIO (const AstRelation * relation) const inline
Definition at line 65 of file IOType.h.
References isInput(), isOutput(), and isPrintSize().
Referenced by souffle::AstSemanticCheckerImpl::checkInlining().
{
         return isInput(relation) || isOutput(relation) || isPrintSize(relation);
     }
isLimitSize()
bool souffle::IOType::isLimitSize (const AstRelation * relation) const inline
Definition at line 53 of file IOType.h.
References limitSizeRelations.
Referenced by souffle::AstToRamTranslator::translateRecursiveRelation().
{
         return limitSizeRelations.count(relation) != 0;
     }
isOutput()
bool souffle::IOType::isOutput (const AstRelation * relation) const inline
Definition at line 45 of file IOType.h.
References outputRelations.
Referenced by souffle::SCCGraphAnalysis::getExternalNonOutputPredecessorRelations(), souffle::SCCGraphAnalysis::getExternalOutputPredecessorRelations(), souffle::SCCGraphAnalysis::getInternalNonOutputRelationsWithExternalSuccessors(), souffle::SCCGraphAnalysis::getInternalOutputRelations(), and isIO().
{
         return outputRelations.count(relation) != 0;
     }
isPrintSize()
bool souffle::IOType::isPrintSize (const AstRelation * relation) const inline
Definition at line 49 of file IOType.h.
References printSizeRelations.
Referenced by isIO().
{
         return printSizeRelations.count(relation) != 0;
     }
print()
void souffle::IOType::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 55 of file IOType.cpp.
References inputRelations, souffle::join(), limitSizeRelations, outputRelations, and printSizeRelations.
Referenced by IOType().
{
     auto show = [](std::ostream& os, const AstRelation* r) { os << r->getQualifiedName(); };
     os << "input relations: {" << join(inputRelations, ", ", show) << "}\n";
     os << "output relations: {" << join(outputRelations, ", ", show) << "}\n";
     os << "printsize relations: {" << join(printSizeRelations, ", ", show) << "}\n";
     os << "limitsize relations: {" << join(limitSizeRelations, ", ", show) << "}\n";
 }
run()
void souffle::IOType::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 32 of file IOType.cpp.
References souffle::AstDirective::getDirective(), souffle::AstTranslationUnit::getProgram(), souffle::AstDirective::getQualifiedName(), souffle::getRelation(), souffle::AstDirective::getType(), souffle::AstDirective::hasDirective(), souffle::input, inputRelations, souffle::limitsize, limitSize, limitSizeRelations, souffle::output, outputRelations, souffle::printsize, printSizeRelations, relation, and souffle::visitDepthFirst().
Referenced by IOType().
{
     const AstProgram& program = *translationUnit.getProgram();
     visitDepthFirst(program, [&](const AstDirective& directive) {
         auto* relation = getRelation(program, directive.getQualifiedName());
         if (relation == nullptr) {
             return;
         }
         switch (directive.getType()) {
             case AstDirectiveType::input: inputRelations.insert(relation); break;
             case AstDirectiveType::output: outputRelations.insert(relation); break;
             case AstDirectiveType::printsize:
                 printSizeRelations.insert(relation);
                 outputRelations.insert(relation);
                 break;
             case AstDirectiveType::limitsize:
                 limitSizeRelations.insert(relation);
                 assert(directive.hasDirective("n") && "limitsize has no n directive");
                 limitSize[relation] = stoi(directive.getDirective("n"));
                 break;
         }
     });
 }
Field Documentation
inputRelations
std::set<const AstRelation*> souffle::IOType::inputRelations private
Definition at line 70 of file IOType.h.
Referenced by isInput(), print(), and run().
limitSize
std::map<const AstRelation*, std::size_t> souffle::IOType::limitSize private
Definition at line 74 of file IOType.h.
Referenced by getLimitSize(), and run().
limitSizeRelations
std::set<const AstRelation*> souffle::IOType::limitSizeRelations private
Definition at line 73 of file IOType.h.
Referenced by isLimitSize(), print(), and run().
name
constexpr const char* souffle::IOType::name = "IO-type-analysis" static
Definition at line 33 of file IOType.h.
outputRelations
std::set<const AstRelation*> souffle::IOType::outputRelations private
Definition at line 71 of file IOType.h.
Referenced by isOutput(), print(), and run().
printSizeRelations
std::set<const AstRelation*> souffle::IOType::printSizeRelations private
Definition at line 72 of file IOType.h.
Referenced by isPrintSize(), print(), and run().
The documentation for this class was generated from the following files:
ast/analysis/IOType.h
ast/analysis/IOType.cpp