souffle: souffle::IOAttributesTransformer Class Reference
souffle::IOAttributesTransformer Class Reference
Transformation pass to set attribute names and types in IO operations.
#include <IOAttributes.h>
Public Member Functions
IOAttributesTransformer * clone () const override
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
json11::Json getAlgebraicDataTypes (AstTranslationUnit &translationUnit) const
Get sum types info for IO.
json11::Json getRecordsParams (AstTranslationUnit &translationUnit) const
json11::Json getRecordsTypes (AstTranslationUnit &translationUnit) const
std::string getRelationName (const AstDirective *node)
bool setAttributeNames (AstTranslationUnit &translationUnit)
bool setAttributeParams (AstTranslationUnit &translationUnit)
bool setAttributeTypes (AstTranslationUnit &translationUnit)
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to set attribute names and types in IO operations.
Definition at line 53 of file IOAttributes.h.
Member Function Documentation
clone()
IOAttributesTransformer* souffle::IOAttributesTransformer::clone () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 59 of file IOAttributes.h.
{
         return new IOAttributesTransformer();
     }
getAlgebraicDataTypes()
json11::Json souffle::IOAttributesTransformer::getAlgebraicDataTypes (AstTranslationUnit & translationUnit) const inline private
Get sum types info for IO.
If they don't exists - create them.
The structure of JSON is approximately: {"ADTs" : {ADT_NAME : {"branches" : [branch..]}, {"arity": ...}}} branch = {{"types": [types ...]}, ["name": ...]}
Definition at line 187 of file IOAttributes.h.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AlgebraicDataType::getBranches(), souffle::AstTranslationUnit::getProgram(), souffle::getTypeQualifier(), souffle::AstProgram::getTypes(), json11::Json::is_null(), and souffle::visitDepthFirst().
Referenced by setAttributeTypes().
{
         static json11::Json sumTypesInfo;
         // Check if the types were already constructed
         if (!sumTypesInfo.is_null()) {
             return sumTypesInfo;
         }
         AstProgram& program = *translationUnit.getProgram();
         auto& typeEnv = translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
         std::map<std::string, json11::Json> sumTypes;
         visitDepthFirst(program.getTypes(), [&](const AstAlgebraicDataType& astAlgebraicDataType) {
             auto& sumType = dynamic_cast<const AlgebraicDataType&>(typeEnv.getType(astAlgebraicDataType));
             auto& branches = sumType.getBranches();
             std::vector<json11::Json> branchesInfo;
             for (const auto& branch : branches) {
                 std::vector<json11::Json> branchTypes;
                 for (auto* type : branch.types) {
                     branchTypes.push_back(getTypeQualifier(*type));
                 }
                 auto branchInfo =
                         json11::Json::object{{{"types", std::move(branchTypes)}, {"name", branch.name}}};
                 branchesInfo.push_back(std::move(branchInfo));
             }
             auto typeQualifier = getTypeQualifier(sumType);
             auto&& sumInfo = json11::Json::object{{{"branches", std::move(branchesInfo)},
                     {"arity", static_cast<long long>(branches.size())}}};
             sumTypes.emplace(std::move(typeQualifier), std::move(sumInfo));
         });
         sumTypesInfo = json11::Json(sumTypes);
         return sumTypesInfo;
     }
getName()
std::string souffle::IOAttributesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 55 of file IOAttributes.h.
{
         return "IOAttributesTransformer";
     }
getRecordsParams()
json11::Json souffle::IOAttributesTransformer::getRecordsParams (AstTranslationUnit & translationUnit) const inline private
Definition at line 260 of file IOAttributes.h.
References souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getTypes(), and json11::Json::is_null().
Referenced by setAttributeParams().
{
         static json11::Json ramRecordParams;
         // Check if the types where already constructed
         if (!ramRecordParams.is_null()) {
             return ramRecordParams;
         }
         AstProgram* program = translationUnit.getProgram();
         std::vector<std::string> elementParams;
         std::map<std::string, json11::Json> records;
         // Iterate over all record types in the program populating the records map.
         for (auto* astType : program->getTypes()) {
             if (isA<AstRecordType>(astType)) {
                 elementParams.clear();
                 for (const auto field : as<AstRecordType>(astType)->getFields()) {
                     elementParams.push_back(field->getName());
                 }
                 const size_t recordArity = elementParams.size();
                 json11::Json recordInfo = json11::Json::object{
                         {"params", std::move(elementParams)}, {"arity", static_cast<long long>(recordArity)}};
                 records.emplace(astType->getQualifiedName().toString(), std::move(recordInfo));
             }
         }
         ramRecordParams = json11::Json(records);
         return ramRecordParams;
     }
getRecordsTypes()
json11::Json souffle::IOAttributesTransformer::getRecordsTypes (AstTranslationUnit & translationUnit) const inline private
Definition at line 228 of file IOAttributes.h.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::getTypeQualifier(), souffle::AstProgram::getTypes(), and json11::Json::is_null().
Referenced by setAttributeTypes().
{
         static json11::Json ramRecordTypes;
         // Check if the types where already constructed
         if (!ramRecordTypes.is_null()) {
             return ramRecordTypes;
         }
         AstProgram* program = translationUnit.getProgram();
         auto typeEnv = &translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
         std::vector<std::string> elementTypes;
         std::map<std::string, json11::Json> records;
         // Iterate over all record types in the program populating the records map.
         for (auto* astType : program->getTypes()) {
             const auto& type = typeEnv->getType(*astType);
             if (isA<RecordType>(type)) {
                 elementTypes.clear();
                 for (const Type* field : as<RecordType>(type)->getFields()) {
                     elementTypes.push_back(getTypeQualifier(*field));
                 }
                 const size_t recordArity = elementTypes.size();
                 json11::Json recordInfo = json11::Json::object{
                         {"types", std::move(elementTypes)}, {"arity", static_cast<long long>(recordArity)}};
                 records.emplace(getTypeQualifier(type), std::move(recordInfo));
             }
         }
         ramRecordTypes = json11::Json(records);
         return ramRecordTypes;
     }
getRelationName()
std::string souffle::IOAttributesTransformer::getRelationName (const AstDirective * node) inline private
Definition at line 175 of file IOAttributes.h.
References souffle::AstDirective::getQualifiedName(), souffle::AstQualifiedName::getQualifiers(), souffle::join(), and souffle::toString().
{
         return toString(join(node->getQualifiedName().getQualifiers(), "."));
     }
setAttributeNames()
bool souffle::IOAttributesTransformer::setAttributeNames (AstTranslationUnit & translationUnit) inline private
Definition at line 107 of file IOAttributes.h.
References souffle::Global::config(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstRelation::getAttributes(), souffle::AstProgram::getDirectives(), souffle::AstTranslationUnit::getProgram(), souffle::getRelation(), souffle::join(), souffle::limitsize, and souffle::toString().
Referenced by transform().
{
         bool changed = false;
         AstProgram* program = translationUnit.getProgram();
         for (AstDirective* io : program->getDirectives()) {
             if (io->getType() == AstDirectiveType::limitsize) {
                 continue;
             }
             if (io->hasDirective("attributeNames")) {
                 continue;
             }
             AstRelation* rel = getRelation(*translationUnit.getProgram(), io->getQualifiedName());
             std::string delimiter("\t");
             if (io->hasDirective("delimiter")) {
                 delimiter = io->getDirective("delimiter");
             }
             std::vector<std::string> attributeNames;
             for (const auto* attribute : rel->getAttributes()) {
                 attributeNames.push_back(attribute->getName());
             }
             if (Global::config().has("provenance")) {
                 auto auxArityAnalysis = translationUnit.getAnalysis<AuxiliaryArity>();
                 std::vector<std::string> originalAttributeNames(
                         attributeNames.begin(), attributeNames.end() - auxArityAnalysis->getArity(rel));
                 io->addDirective("attributeNames", toString(join(originalAttributeNames, delimiter)));
             } else {
                 io->addDirective("attributeNames", toString(join(attributeNames, delimiter)));
             }
             changed = true;
         }
         return changed;
     }
setAttributeParams()
bool souffle::IOAttributesTransformer::setAttributeParams (AstTranslationUnit & translationUnit) inline private
Definition at line 74 of file IOAttributes.h.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::AstProgram::getDirectives(), souffle::AstTranslationUnit::getProgram(), getRecordsParams(), souffle::getRelation(), and souffle::limitsize.
Referenced by transform().
{
         bool changed = false;
         AstProgram* program = translationUnit.getProgram();
         auto auxArityAnalysis = translationUnit.getAnalysis<AuxiliaryArity>();
         for (AstDirective* io : program->getDirectives()) {
             if (io->getType() == AstDirectiveType::limitsize) {
                 continue;
             }
             AstRelation* rel = getRelation(*translationUnit.getProgram(), io->getQualifiedName());
             // Prepare type system information.
             std::vector<std::string> attributesParams;
             for (const auto* attribute : rel->getAttributes()) {
                 attributesParams.push_back(attribute->getName());
             }
             // Casting due to json11.h type requirements.
             long long arity{static_cast<long long>(rel->getArity() - auxArityAnalysis->getArity(rel))};
             long long auxArity{static_cast<long long>(auxArityAnalysis->getArity(rel))};
             json11::Json relJson = json11::Json::object{{"arity", arity}, {"auxArity", auxArity},
                     {"params", json11::Json::array(attributesParams.begin(), attributesParams.end())}};
             json11::Json params = json11::Json::object{
                     {"relation", relJson}, {"records", getRecordsParams(translationUnit)}};
             io->addDirective("params", params.dump());
             changed = true;
         }
         return changed;
     }
setAttributeTypes()
bool souffle::IOAttributesTransformer::setAttributeTypes (AstTranslationUnit & translationUnit) inline private
Definition at line 141 of file IOAttributes.h.
References getAlgebraicDataTypes(), souffle::AstTranslationUnit::getAnalysis(), souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::AstProgram::getDirectives(), souffle::AstTranslationUnit::getProgram(), getRecordsTypes(), souffle::getRelation(), souffle::getTypeQualifier(), and types.
Referenced by transform().
{
         bool changed = false;
         AstProgram* program = translationUnit.getProgram();
         auto auxArityAnalysis = translationUnit.getAnalysis<AuxiliaryArity>();
         auto typeEnv = &translationUnit.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment();
         for (AstDirective* io : program->getDirectives()) {
             AstRelation* rel = getRelation(*translationUnit.getProgram(), io->getQualifiedName());
             // Prepare type system information.
             std::vector<std::string> attributesTypes;
             for (const auto* attribute : rel->getAttributes()) {
                 auto typeName = attribute->getTypeName();
                 auto type = getTypeQualifier(typeEnv->getType(typeName));
                 attributesTypes.push_back(type);
             }
             // Casting due to json11.h type requirements.
             long long arity{static_cast<long long>(rel->getArity() - auxArityAnalysis->getArity(rel))};
             long long auxArity{static_cast<long long>(auxArityAnalysis->getArity(rel))};
             json11::Json relJson = json11::Json::object{{"arity", arity}, {"auxArity", auxArity},
                     {"types", json11::Json::array(attributesTypes.begin(), attributesTypes.end())}};
             json11::Json types =
                     json11::Json::object{{"relation", relJson}, {"records", getRecordsTypes(translationUnit)},
                             {"ADTs", getAlgebraicDataTypes(translationUnit)}};
             io->addDirective("types", types.dump());
             changed = true;
         }
         return changed;
     }
transform()
bool souffle::IOAttributesTransformer::transform (AstTranslationUnit & translationUnit) inline override private virtual
Implements souffle::AstTransformer.
Definition at line 64 of file IOAttributes.h.
References setAttributeNames(), setAttributeParams(), and setAttributeTypes().
{
         bool changed = false;
         changed |= setAttributeNames(translationUnit);
         changed |= setAttributeTypes(translationUnit);
         changed |= setAttributeParams(translationUnit);
         return changed;
     }
The documentation for this class was generated from the following file:
ast/transform/IOAttributes.h