souffle: souffle::TypeChecker Class Reference
souffle::TypeChecker Class Reference
Public Member Functions
void run ()
Analyse types, clause by clause.
TypeChecker (AstTranslationUnit &tu)
Private Member Functions
void visitAggregator (const AstAggregator &aggregator) override
void visitAtom (const AstAtom &atom) override
void visitBinaryConstraint (const AstBinaryConstraint &constraint) override
void visitBranchInit (const AstBranchInit &adt) override
void visitIntrinsicFunctor (const AstIntrinsicFunctor &fun) override
void visitNilConstant (const AstNilConstant &constant) override
void visitNumericConstant (const AstNumericConstant &constant) override
void visitRecordInit (const AstRecordInit &rec) override
void visitStringConstant (const AstStringConstant &constant) override
void visitTypeCast (const AstTypeCast &cast) override
void visitUserDefinedFunctor (const AstUserDefinedFunctor &fun) override
void visitVariable (const AstVariable &var) override
Private Member Functions inherited from souffle::AstVisitor< void >
void operator() (const AstNode &node, Params... args)
The main entry for the user allowing visitors to be utilized as functions.
virtual void visit (const AstNode &node, Params... args)
The main entry for a visit process conducting the dispatching of a visit to the various sub-types of AstNodes.
virtual ~AstVisitor ()=default
A virtual destructor.
LINK (SubsetType, Type)
LINK (RecordType, Type)
LINK (AlgebraicDataType, Type)
LINK (UnionType, Type)
LINK (Type, Node)
LINK (Argument, Node)
LINK (Literal, Node)
LINK (ComponentType, Node)
LINK (ComponentInit, Node)
LINK (Component, Node)
LINK (Program, Node)
LINK (Attribute, Node)
LINK (Clause, Node)
LINK (Relation, Node)
LINK (Pragma, Node)
virtual void visitNode (const AstNode &, Params...)
The base case for all visitors – if no more specific overload was defined.
Private Attributes
const AstProgram & program = *tu.getProgram()
ErrorReport & report = tu.getErrorReport()
AstTranslationUnit & tu
const TypeAnalysis & typeAnalysis = *tu.getAnalysis<TypeAnalysis>()
const TypeEnvironment & typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment()
Detailed Description
Definition at line 145 of file SemanticChecker.cpp.
Constructor & Destructor Documentation
TypeChecker()
souffle::TypeChecker::TypeChecker (AstTranslationUnit & tu) inline
Definition at line 147 of file SemanticChecker.cpp.
 : tu(tu){};
Member Function Documentation
run()
void souffle::TypeChecker::run () inline
Analyse types, clause by clause.
Definition at line 150 of file SemanticChecker.cpp.
References souffle::AstProgram::getClauses(), souffle::AstTranslationUnit::getProgram(), and souffle::visitDepthFirstPreOrder().
                {
         for (auto* clause : tu.getProgram()->getClauses()) {
             visitDepthFirstPreOrder(*clause, *this);
         }
     }
visitAggregator()
void souffle::TypeChecker::visitAggregator (const AstAggregator & aggregator) override private
Definition at line 1558 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstAggregator::getOperator(), souffle::AstNode::getSrcLoc(), souffle::getTypeAttributeAggregate(), souffle::TypeAnalysis::getTypes(), and souffle::isOfKind().
{
     auto op = aggregator.getOperator();
     auto aggregatorType = typeAnalysis.getTypes(&aggregator);
     TypeAttribute opType = getTypeAttributeAggregate(op);
     // Check if operation type and return type agree.
     if (!isOfKind(aggregatorType, opType)) {
         report.addError("Couldn't assign types to the aggregator", aggregator.getSrcLoc());
     }
 }
visitAtom()
void souffle::TypeChecker::visitAtom (const AstAtom & atom) override private
Definition at line 1276 of file SemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::all_of(), souffle::Global::config(), souffle::Diagnostic::ERROR, tinyformat::format(), souffle::AstAtom::getArguments(), souffle::getAtomRelation(), souffle::TypeEnvironment::getType(), souffle::TypeAnalysis::getTypes(), i, souffle::isSubtypeOf(), souffle::TypeEnvironment::isType(), and relation.
{
     auto relation = getAtomRelation(&atom, &program);
     if (relation == nullptr) {
         return;  // error unrelated to types.
     }
     auto attributes = relation->getAttributes();
     auto arguments = atom.getArguments();
     if (attributes.size() != arguments.size()) {
         return;  // error in input program
     }
     for (size_t i = 0; i < attributes.size(); ++i) {
         auto& typeName = attributes[i]->getTypeName();
         if (typeEnv.isType(typeName)) {
             auto argTypes = typeAnalysis.getTypes(arguments[i]);
             auto& attributeType = typeEnv.getType(typeName);
             if (argTypes.isAll() || argTypes.empty()) {
                 continue;  // This will be reported later.
             }
             // Attribute and argument type agree if, argument type is a subtype of declared type
             // or is of the appropriate constant type or the (constant) record type.
             bool validAttribute = all_of(argTypes, [&attributeType](const Type& type) {
                 if (isSubtypeOf(type, attributeType)) return true;
                 if (!isSubtypeOf(attributeType, type)) return false;
                 if (isA<ConstantType>(type)) return true;
                 return isA<RecordType>(type) && !isA<SubsetType>(type);
             });
             if (!validAttribute && !Global::config().has("legacy")) {
                 auto primaryDiagnostic =
                         DiagnosticMessage("Atom's argument type is not a subtype of its declared type",
                                 arguments[i]->getSrcLoc());
                 auto declaredTypeInfo =
                         DiagnosticMessage(tfm::format("The argument's declared type is %s", typeName),
                                 attributes[i]->getSrcLoc());
                 report.addDiagnostic(Diagnostic(Diagnostic::Type::ERROR, std::move(primaryDiagnostic),
                         {std::move(declaredTypeInfo)}));
             }
         }
     }
 }
visitBinaryConstraint()
void souffle::TypeChecker::visitBinaryConstraint (const AstBinaryConstraint & constraint) override private
Definition at line 1509 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::any_of(), souffle::areEquivalentTypes(), souffle::TypeSet::begin(), souffle::Float, souffle::getBinaryConstraintTypes(), souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), souffle::isOfKind(), souffle::isOrderedBinaryConstraintOp(), souffle::join(), souffle::Record, souffle::Signed, souffle::profile::ss, souffle::Symbol, and souffle::Unsigned.
{
     auto op = constraint.getOperator();
     auto left = constraint.getLHS();
     auto right = constraint.getRHS();
     auto opTypesAttrs = getBinaryConstraintTypes(op);
     auto leftTypes = typeAnalysis.getTypes(left);
     auto rightTypes = typeAnalysis.getTypes(right);
     // Skip checks if either side is `Bottom` b/c it just adds noise.
     // The unable-to-deduce-type checker will point out the issue.
     if (leftTypes.empty() || rightTypes.empty() || leftTypes.isAll() || rightTypes.isAll()) return;
     assert((leftTypes.size() == 1) && (rightTypes.size() == 1));
     // Extract types from singleton sets.
     auto& leftType = *typeAnalysis.getTypes(left).begin();
     auto& rightType = *typeAnalysis.getTypes(right).begin();
     // give them a slightly nicer error
     if (isOrderedBinaryConstraintOp(op) && !areEquivalentTypes(leftType, rightType)) {
         report.addError("Cannot compare different types", constraint.getSrcLoc());
     } else {
         auto checkTyAttr = [&](AstArgument const& side) {
             auto opMatchesType = any_of(opTypesAttrs,
                     [&](auto& typeAttr) { return isOfKind(typeAnalysis.getTypes(&side), typeAttr); });
             if (!opMatchesType) {
                 std::stringstream ss;
                 ss << "Constraint requires an operand of type "
                    << join(opTypesAttrs, " or ", [&](auto& out, auto& typeAttr) {
                           switch (typeAttr) {
                               case TypeAttribute::Signed: out << "`number`"; break;
                               case TypeAttribute::Symbol: out << "`symbol`"; break;
                               case TypeAttribute::Unsigned: out << "`unsigned`"; break;
                               case TypeAttribute::Float: out << "`float`"; break;
                               case TypeAttribute::Record: out << "a record"; break;
                               case TypeAttribute::ADT: out << "a sum"; break;
                           }
                       });
                 report.addError(ss.str(), side.getSrcLoc());
             }
         };
         checkTyAttr(*left);
         checkTyAttr(*right);
     }
 }
visitBranchInit()
void souffle::TypeChecker::visitBranchInit (const AstBranchInit & adt) override private
Definition at line 1388 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::all_of(), souffle::TypeSet::begin(), souffle::AstTerm::getArguments(), souffle::AstBranchInit::getConstructor(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), i, souffle::TypeSet::isAll(), souffle::isOfKind(), souffle::isSubtypeOf(), souffle::TypeSet::size(), and types.
{
     TypeSet types = typeAnalysis.getTypes(&adt);
     if (!isOfKind(types, TypeAttribute::ADT) || types.isAll() || types.size() != 1) {
         report.addError("Ambiguous branch", adt.getSrcLoc());
         return;
     }
     // We know now that the set "types" is a singleton
     auto& sumType = *as<AlgebraicDataType>(*types.begin());
     auto& argsDeclaredTypes = sumType.getBranchTypes(adt.getConstructor());
     auto args = adt.getArguments();
     if (argsDeclaredTypes.size() != args.size()) {
         // Invalid branchInit arity, handled by checkBranchInits.
         return;
     }
     for (size_t i = 0; i < args.size(); ++i) {
         auto argTypes = typeAnalysis.getTypes(args[i]);
         bool correctType =
                 all_of(argTypes, [&](const Type& t) { return isSubtypeOf(t, *argsDeclaredTypes[i]); });
         if (!correctType) {
             // TODO (darth_tytus): Give better error
             report.addError("Branch argument's type doesn't match its declared type", args[i]->getSrcLoc());
         }
     }
 }
visitIntrinsicFunctor()
void souffle::TypeChecker::visitIntrinsicFunctor (const AstIntrinsicFunctor & fun) override private
Definition at line 1449 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstTerm::getArguments(), souffle::AstIntrinsicFunctor::getFunction(), souffle::AstIntrinsicFunctor::getFunctionInfo(), souffle::AstNode::getSrcLoc(), souffle::isValidFunctorOpArity(), and souffle::validOverloads().
{
     if (!fun.getFunctionInfo()) {  // no info => no overload found during inference
         auto args = fun.getArguments();
         if (!isValidFunctorOpArity(fun.getFunction(), args.size())) {
             report.addError("invalid overload (arity mismatch)", fun.getSrcLoc());
             return;
         }
         assert(validOverloads(typeAnalysis, fun).empty() && "polymorphic transformation wasn't applied?");
         report.addError("no valid overloads", fun.getSrcLoc());
     }
 }
visitNilConstant()
void souffle::TypeChecker::visitNilConstant (const AstNilConstant & constant) override private
Definition at line 1363 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), souffle::isOfKind(), souffle::Record, and types.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Record)) {
         report.addError("Nil constant used as a non-record", constant.getSrcLoc());
         return;
     }
 }
visitNumericConstant()
void souffle::TypeChecker::visitNumericConstant (const AstNumericConstant & constant) override private
Definition at line 1335 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::Float, souffle::AstNumericConstant::Float, souffle::AstNode::getSrcLoc(), souffle::AstNumericConstant::getType(), souffle::TypeAnalysis::getTypes(), souffle::AstNumericConstant::Int, souffle::isOfKind(), souffle::Signed, types, souffle::AstNumericConstant::Uint, and souffle::Unsigned.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     // No type could be assigned.
     if (!constant.getType().has_value()) {
         report.addError("Ambiguous constant (unable to deduce type)", constant.getSrcLoc());
         return;
     }
     switch (*constant.getType()) {
         case AstNumericConstant::Type::Int:
             if (!isOfKind(types, TypeAttribute::Signed)) {
                 report.addError("Number constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case AstNumericConstant::Type::Uint:
             if (!isOfKind(types, TypeAttribute::Unsigned)) {
                 report.addError("Unsigned constant (type mismatch)", constant.getSrcLoc());
             }
             break;
         case AstNumericConstant::Type::Float:
             if (!isOfKind(types, TypeAttribute::Float)) {
                 report.addError("Float constant (type mismatch)", constant.getSrcLoc());
             }
             break;
     }
 }
visitRecordInit()
void souffle::TypeChecker::visitRecordInit (const AstRecordInit & rec) override private
Definition at line 1371 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::TypeSet::begin(), souffle::AstTerm::getArguments(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), souffle::isOfKind(), souffle::Record, souffle::TypeSet::size(), and types.
{
     TypeSet types = typeAnalysis.getTypes(&rec);
     if (!isOfKind(types, TypeAttribute::Record) || types.size() != 1) {
         report.addError("Ambiguous record", rec.getSrcLoc());
         return;
     }
     // At this point we know that there is exactly one type in set, so we can take it.
     auto& recordType = *as<RecordType>(*types.begin());
     if (recordType.getFields().size() != rec.getArguments().size()) {
         report.addError("Wrong number of arguments given to record", rec.getSrcLoc());
         return;
     }
 }
visitStringConstant()
void souffle::TypeChecker::visitStringConstant (const AstStringConstant & constant) override private
Definition at line 1328 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), souffle::isOfKind(), souffle::Symbol, and types.
{
     TypeSet types = typeAnalysis.getTypes(&constant);
     if (!isOfKind(types, TypeAttribute::Symbol)) {
         report.addError("Symbol constant (type mismatch)", constant.getSrcLoc());
     }
 }
visitTypeCast()
void souffle::TypeChecker::visitTypeCast (const AstTypeCast & cast) override private
Definition at line 1418 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), tinyformat::format(), souffle::AstNode::getSrcLoc(), souffle::AstTypeCast::getType(), souffle::TypeAnalysis::getTypes(), souffle::AstTypeCast::getValue(), souffle::haveCommonSupertype(), and souffle::TypeEnvironment::isType().
{
     if (!typeEnv.isType(cast.getType())) {
         report.addError(
                 tfm::format("Type cast to the undeclared type \"%s\"", cast.getType()), cast.getSrcLoc());
         return;
     }
     auto& castTypes = typeAnalysis.getTypes(&cast);
     auto& argTypes = typeAnalysis.getTypes(cast.getValue());
     if (castTypes.isAll() || castTypes.size() != 1) {
         report.addError("Unable to deduce type of the argument (cast)", cast.getSrcLoc());
         return;
     }
     // This should be reported elsewhere
     if (argTypes.isAll() || castTypes.size() != 1) {
         return;
     }
     // We know that both sets have size 1.
     auto& castTy = *castTypes.begin();
     auto& argTy = *argTypes.begin();
     if (!haveCommonSupertype(castTy, argTy)) {
         report.addError(
                 tfm::format(R"(Type "%s" can't be converted to "%s")", argTy, castTy), cast.getSrcLoc());
         return;
     }
 }
visitUserDefinedFunctor()
void souffle::TypeChecker::visitUserDefinedFunctor (const AstUserDefinedFunctor & fun) override private
Definition at line 1462 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ADT, souffle::fatal(), souffle::Float, souffle::AstUserDefinedFunctor::getArgType(), souffle::AstTerm::getArguments(), souffle::AstUserDefinedFunctor::getReturnType(), souffle::AstNode::getSrcLoc(), souffle::TypeAnalysis::getTypes(), i, souffle::isOfKind(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
     // check type of result
     const TypeSet& resultType = typeAnalysis.getTypes(&fun);
     if (!isOfKind(resultType, fun.getReturnType())) {
         switch (fun.getReturnType()) {
             case TypeAttribute::Signed:
                 report.addError("Non-numeric use for numeric functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Unsigned:
                 report.addError("Non-unsigned use for unsigned functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Float:
                 report.addError("Non-float use for float functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Symbol:
                 report.addError("Non-symbolic use for symbolic functor", fun.getSrcLoc());
                 break;
             case TypeAttribute::Record: fatal("Invalid return type");
             case TypeAttribute::ADT: fatal("Invalid return type");
         }
     }
     size_t i = 0;
     for (auto arg : fun.getArguments()) {
         if (!isOfKind(typeAnalysis.getTypes(arg), fun.getArgType(i))) {
             switch (fun.getArgType(i)) {
                 case TypeAttribute::Signed:
                     report.addError("Non-numeric argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Symbol:
                     report.addError("Non-symbolic argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Unsigned:
                     report.addError("Non-unsigned argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Float:
                     report.addError("Non-float argument for functor", arg->getSrcLoc());
                     break;
                 case TypeAttribute::Record: fatal("Invalid argument type");
                 case TypeAttribute::ADT: fatal("Invalid argument type");
             }
         }
         ++i;
     }
 }
visitVariable()
void souffle::TypeChecker::visitVariable (const AstVariable & var) override private
Definition at line 1322 of file SemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::TypeSet::empty(), souffle::AstVariable::getName(), souffle::AstNode::getSrcLoc(), and souffle::TypeAnalysis::getTypes().
{
     if (typeAnalysis.getTypes(&var).empty()) {
         report.addError("Unable to deduce type for variable " + var.getName(), var.getSrcLoc());
     }
 }
Field Documentation
program
const AstProgram& souffle::TypeChecker::program = *tu.getProgram() private
Definition at line 161 of file SemanticChecker.cpp.
report
ErrorReport& souffle::TypeChecker::report = tu.getErrorReport() private
Definition at line 158 of file SemanticChecker.cpp.
tu
AstTranslationUnit& souffle::TypeChecker::tu private
Definition at line 157 of file SemanticChecker.cpp.
typeAnalysis
const TypeAnalysis& souffle::TypeChecker::typeAnalysis = *tu.getAnalysis<TypeAnalysis>() private
Definition at line 159 of file SemanticChecker.cpp.
typeEnv
const TypeEnvironment& souffle::TypeChecker::typeEnv = tu.getAnalysis<TypeEnvironmentAnalysis>()->getTypeEnvironment() private
Definition at line 160 of file SemanticChecker.cpp.
The documentation for this class was generated from the following file:
ast/transform/SemanticChecker.cpp